# Generated by Django 4.2.13 on 2025-01-16 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loghero", "0002_alter_log_extra_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="log",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("success", "Success"),
                    ("failed", "Failed"),
                    ("started", "Started"),
                ],
                default="pending",
                max_length=255,
            ),
        ),
    ]
