# Generated by Django 5.2 on 2025-04-23 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loghero", "0003_alter_log_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="log",
            name="actor_label",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
